[[redirects]]
  from = "/es*"
  to = "https://laszloscheers/es/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/en/*"
  to = "https://laszloscheers/en/:splat"
  status = 200
  force = true